substitutions:
  esp_name: "Remote"

esphome:
  name: esp32-menu-oled

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Xeut6ZwHEVnJsw17x9a43EA0ODIQ3HzHeCmzJtwszwc="

ota:
  password: "e06d8a7f2a0e4dce779d560120aae271"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_name}"
    password: ""
captive_portal:




globals: 
  - id: wifi_connection
    type: bool
    restore_value: no
    initial_value: "false"
sensor:
  - platform: homeassistant
    entity_id: sensor.average_indoor_temperature
    id: avg_temp
    internal: true
  - platform: homeassistant
    entity_id: sensor.bedroom_temperature
    id: temp_br
    internal: true
binary_sensor:
  - platform: homeassistant
    id: br_lamp
    entity_id: light.bedroom_lamp
    internal: true
  - platform: homeassistant
    id: br_tv
    entity_id: switch.samsung_8_series_55
    internal: true
  - platform: homeassistant
    id: flood
    entity_id: switch.back_flood_lights_switch_1
    internal: true
  - platform: homeassistant
    id: bunny
    entity_id: switch.office_light
    internal: true
### Joystick button
  - platform: gpio
    pin: 5
    name: "${esp_name} Select"
    id: ctr
    on_press:
      - display.page.show_next: oled
    internal: true
  - platform: gpio
    pin: 21 
    name: "${esp_name} Left"
    id: lft
    on_press:
      homeassistant.service:
        service: switch.toggle
        data:
          entity_id: switch.samsung_8_series_55
    internal: true
  - platform: gpio
    pin: 18
    name: "${esp_name} Right"
    id: rt
    on_press:
      homeassistant.service:
        service: switch.toggle
        data:
          entity_id: switch.back_flood_lights_switch_1
    internal: true
  - platform: gpio
    pin: 19
    name: "${esp_name} Down"
    id: dwn
    on_press:
      homeassistant.service:
        service: switch.toggle
        data:
          entity_id: switch.office_light
    internal: true
  - platform: gpio
    pin: 17
    name: "${esp_name} Up"
    id: up
    on_press:
      homeassistant.service:
        service: light.toggle
        data:
          entity_id: light.bedroom_lamp
    internal: true
switch:
  - platform: template
    name: "${esp_name} OLED"
    optimistic: true
    turn_on_action:
      - lambda: id(oled).turn_on();
    turn_off_action:
      - lambda: id(oled).turn_off();

time:
  - platform: homeassistant
    id: esptime
interval: 
  - interval: 10s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - lambda: |-
                id(wifi_connection) = true;
          else:
            - lambda: |-
                id(wifi_connection) = false;
font:
  - file: 'fonts/mdi.ttf'
    id: mdi11
    size: 26
    glyphs:
      - "\U000F1B20"
      - "\U000F1B1F"
      - "\U000F07F4"
      - "\U000F083A"
      - "\U000F1987"
      - "\U000F073A"
      - "\U000F1A62"
      - "\U000F1798"
      - "\U000F1A61"
      - "\U000F1797"
  - file: "fonts/mdi.ttf"
    id: mdi2
    size: 17
    glyphs: [
      "\U000F05A9", #wifi
      "\U000F05AA", #no wifi
      ]
  - file: 'fonts/mdi.ttf'
    id: mdi3
    size: 36
    glyphs:
      - "\U000F073A"
  - file: 'fonts/arial.ttf'
    id: font11
    size: 11
  - file: 'fonts/arial.ttf'
    id: font16
    size: 15
  - file: 'fonts/arial.ttf'
    id: font8
    size: 10
graph:
  - id: oled_graph
    duration: 1h
    x_grid: 10min
    y_grid: 1.8     # degC/div
    width: 124
    height: 46
    traces:
      - sensor: temp_br
        line_type: DASHED
        line_thickness: 2
      - sensor: avg_temp
        line_type: DOTTED
        line_thickness: 2
animation:
  - file: "gif/stars2.gif"
    id: stars
i2c:
  sda: 22
  scl: 23
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    id: oled
    address: 0x3C
    brightness: 100%
    rotation: 0
    pages:
      - id: page1
        lambda: |-
          it.rectangle(0, 0, 128, 64);
          //time 
          it.strftime(96, 1, id(font11), "%H:%M", id(esptime).now());
          it.line(94, 0, 94, 13);
          it.line(94, 13, 128, 13);
          // top section
          if (id(br_lamp).state == (1)) {
          it.print(40, 1, id(mdi11), "\U000F1B20");
          } else {
          it.print(40, 1, id(mdi11), "\U000F1B1F");
          }
          it.print(42, 24, id(font8), "Bed");
          // left section
          if (id(br_tv).state == (1)) {
          it.print(1, 18, id(mdi11), "\U000F07F4");
          } else {
          it.print(1, 18, id(mdi11), "\U000F083A");
          }
          it.print(4, 40, id(font8), "T.V.");   
          // Right side
          if (id(flood).state == (1)) {
          it.print(74, 18, id(mdi11), "\U000F1987");
          } else {
          it.print(74, 18, id(mdi11), "\U000F1987");
          it.print(71, 12, id(mdi3), "\U000F073A");
          }
          it.print(75, 40, id(font8), "Flood");
          // bottom
          if (id(bunny).state == (1)) {
          it.print(31, 38, id(mdi11), "\U000F1A61");
          it.print(48, 38, id(mdi11), "\U000F1798");
          } else {
          it.print(31, 38, id(mdi11), "\U000F1A62");
          it.print(49, 40, id(mdi11), "\U000F1797");
          }
          it.printf(110, 44, id(mdi2), "%s", id(wifi_connection) ? "\U000F05A9" : "\U000F05AA");
          it.line(110, 42, 128, 42);
          it.line(110, 42, 110, 64);

      - id: page2
        lambda: |-
          it.rectangle(0, 0, 128, 64);
          it.graph(2, 16, id(oled_graph));
          it.print(16, 0, id(font16), "Temperatures");
      - id: page3
        lambda: |-
          
          id(stars).next_frame();
          
          it.image(0, 0, id(stars), COLOR_ON, COLOR_OFF);





